### ISSUE TITLE
Pundit is looking for ArrayPolicy when the object is mapped

### ISSUE THREAD

**Issue by msdundar** [varvet/pundit#175]
Hi,

I have these controller and policy structure in my application. However, pundit is looking for ArrayPolicy and throwing "Pundit::NotDefinedError at /orders unable to find policy ArrayPolicy for..." error.

**app/controllers/orders_controller.rb =>**

``` ruby
def index
  if current_user.is_staff?
    @orders = Order.all.map{|k| k.transaction}.keep_if{ |a| a != nil }
    authorize @orders, :index_general?
  else
    @user_orders = Order.where(user_id: current_user.id)
    ## The order transactions is empty or not?
    if @user_orders.map{|k| k.transaction}.select{|a| a != nil }.empty?
      redirect_to new_order_path, notice: 'Henüz ödemesini yaptığınız bir sınav bulunmuyor!'
    else
      ## If order transactions isn't empty, fetch them.
      @orders = @user_orders.map{|k| k.transaction}.keep_if{ |a| a != nil }
      authorize @orders, :index_self?
    end
  end
end
```

**app/policies/order_policy.rb =>**

``` ruby
class OrderPolicy < ApplicationPolicy
  def index_general?
    (user.is_super_admin? || user.is_admin? || user.is_editor?) ? true : false
  end

  def index_self?
    (user.is_student? && !user.is_staff?) ? true : false
  end
end
```

When I copy the codes from order_policy to array_policy everything is working fine but ArrayPolicy is an awkward name and I want to keep it as OrderPolicy.

Any ideas?

**Comment by jontonsoup** [comment]
@thomasklemm I don't think headless policies properly address this issue. 

If i submit an array of objects (not created through activerecord), pundit should authorize on each of the objects in the array (not the array itself).

**Comment by jnicklas** [comment]
@jontonsoup I disagree that this would be expected behaviour. Pundit certainly could have that feature, but it does not, and whether it should is arguable. Personally I'm don't think it's a good idea. It blurs the lines and raises questions unnecessarily.

**Comment by jontonsoup** [comment]
@jnicklas I think the confusion is around activerecord relations. I would expect any activerecord relation object to have an activerecord relation policy in the same way that we have an array policy. Pundit automatically figures out what the underlying object for the relation is, why should it not do the same for arrays?

The confusing part is that essentially the same client code has two different behaviors: 

Client code: 
```
@user.comments
```

which is implemented in rails with an activerecord relation:

```
class User 
    has_many :articles
    has_many :comments, though: :articles
end

```

which has different behavior than 

```
def comments
    self.articles.map(&:comments).flatten
end
```

My client application code in both scenarios works exactly fine because pundit is smart about activerecord relation objects. It seems like pundit should authorize arrays them in the same way.

**Comment by jnicklas** [comment]
I have no idea what happens when you send in a relation to `authorize`, but if it does anything sensible, then that's purely by accident, and definitely not an intentional feature of Pundit.

**Comment by jontonsoup** [comment]
@jnicklas hahaha fair enough. 

Pundit actually does correctly pass a relation to the correct underlying model. 

It cleans up code from 
```
articles.each do |article|
    authorize article
end

to 

authorize articles
```

But I imagine a large group of people are using it that way, so keep in mind if you make breaking changes. :)

**Comment by jnicklas** [comment]
@jontonsoup I can't imagine that those two would be equivalent, how would that work? At the very least it'd be passing in the relation as an argument to the policy, not each object individually, barring some really weird magic in ActiveRecord, there isn't any code in Pundit which would make this work.

**Comment by jontonsoup** [comment]
@jnicklas I think active record auto serializes the relation into an array when it is used. I'm not 100% sure how pundit acts. 

Were using STI with User ->> Learner. Pundit sees Learner::ActiveRecord_Relation and directs it to our UserPolicy Automatically. 

I did some quick investigation and it seems like pundit works on both ActiveRecord_Relations, and ActiveRecord_Associations_CollectionProxy ies. 

```
     2: def index
     4:     @enrollments = current_user.active_enrollments.includes(
     5:       :attempts,
     6:       :learner,
     7:       :mentor,
     8:       { user_challenges: { attempts: :activity } },
     9:       { program: [:published_challenges, :published_activities] })
    10:
    11:     @enrollments = present @enrollments
    12:     learners = Learner.where(id: @enrollments.map(&:learner).uniq)
    13:     active_record_learners = current_user.learners #this line added for illustration purposes
    14:     binding.pry #pry
 => 15:     authorize learners
    16: end

[1] pry(#<LearnersController>)> learners.class
=> Learner::ActiveRecord_Relation

[2] pry(#<LearnersController>)> active_record_learners.class
=> Learner::ActiveRecord_Associations_CollectionProxy

[3] pry(#<LearnersController>)> @enrollments.map(&:learner).class
=> Array

[5] pry(#<LearnersController>)> authorize learners
  Learner Load (0.9ms)  SELECT "users".* FROM "users" WHERE "users"."type" IN ('Learner') AND "users"."id" IN (129, 26, 51, 88, 39, 241, 153, 87, 5)
  Learner Load (0.9ms)  SELECT "users".* FROM "users" INNER JOIN "enrollments" ON "users"."id" = "enrollments"."learner_id" WHERE "users"."type" IN ('Learner') AND "enrollments"."mentor_id" = $1  [["mentor_id", 1]]
=> true

[6] pry(#<LearnersController>)> authorize 

[9] pry(#<LearnersController>)> active_record_learners
=> [#<Learner:0x007fea05878dd0
  id: 87>,
...]
=> true

[7] pry(#<LearnersController>)> @enrollments.map(&:learner)
=> [#<Learner:0x007fe9dd4e3cd8
  id: 129
  created_at: Thu, 13 Nov 2014 18:31:04 EST -05:00,
  updated_at: Tue, 14 Apr 2015 11:36:21 EDT -04:00>,
 ....]

[8] pry(#<LearnersController>)> authorize @enrollments.map(&:learner)
Pundit::NotDefinedError: unable to find policy ArrayPolicy for....
from /Users/jmfriedm/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/pundit-0.3.0/lib/pundit/policy_finder.rb:28:in `policy!'


```

**Comment by jnicklas** [comment]
Yes, I suspected that Pundit would be able to find the correct policy class given a scope, that's natural because a relation still has information about which class the results of the query will automatically be mapped to. This is mostly a by-product of the fact that we use the same rules to look up scopes. However, I want to emphasize that this is *NOT* the same thing as `authorize` accepting a scope. I just double checked it, and just as I suspected before, `authorize` will *NOT* pass each found record in the scope into the policy individually, rather it will pass the entire scope into the policy. So given a policy like this:

``` ruby
class PersonPolicy
  def initialize(*args)
    p args
  end
end
```

It just prints whatever arguments are passed to initialize, look at what happens when I call `authorize`:

```
[1] pry(#<SiteController>)> authorize(Account.first.people)
[nil, #<ActiveRecord::Associations::CollectionProxy [#<Person id: 2, account_id: 2, user_id: 2, created_at: "2014-11-22 18:02:31", updated_at: "2014-11-22 18:02:31", name: "Elabs McElabs", role: "owner", active: true, group_id: nil, image_id: nil>]>]
=> true
```

You can see that the second argument to initialize is the relation proxy, which contains *ALL* records in the scope.

If you think that's fine, and handle looping over the records in your policy, then that's up to you, but please be aware that Pundit does not handle this for you.

**Comment by jontonsoup** [comment]
That makes sense -- it might be valuable to put a warning in the docs about this behavior, as its not intuitive at first. 

I've been handing this case with a subset checker in my policies  -- which seemed like a reasonable way to validate at the time. 

```ruby 
def subset(x, y)
 (x - y).empty?
end
```
