### ISSUE TITLE
Unable to access namespaced policy in view

### ISSUE THREAD

**Issue by jrmehle** [varvet/pundit#178]
Given a TagsController and an Admin::TagsController each with a corresponding policy, how does one access the admin policy from a view? I've got a global nav link I'd like to only expose to admins.

`policy(Tag).index?` references the non-Admin namespace policy

I assumed something like this would work:  `policy(Admin::Tag).index?` However, Admin::Tag is not defined and thus, it throws an error.

Ideally, I'd do something like so: `policy(Tag, namespace: 'admin').index?`

**Comment by Systho** [comment]
I've been using this module to solve my namespace problem. It is not covered by automated tests (but is used on production ) and I just put it here so that it might help other people. Feel free to use it, change it or say it's crap, it has served me well and it might help you, too :)

https://gist.github.com/Systho/3d7632b5aa999cf88d87

**Comment by hwhelchel** [comment]
What about using simple delegators? 

Let's say we are a news media app with a paywall for articles so we want have a policy for article preview and for the full article. 

```ruby
class Api::ArticlePreviewsController < Api::BaseController

  def index
    respond_with :api, article_previews, each_serializer: ArticlePreviewSerializer
  end

  def show
    respond_with :api, article_preview, serializer: ArticlePreviewSerializer
  end

  private

  def article_previews
    @article_previews ||= policy_scope ArticlePreview.new(Article)
  end

  def article_preview
    @article_preview ||= authorize ArticlePreview.new(Article.find(params[:id]))
  end
end
```

```ruby
class ArticlePreview < SimpleDelegator; end
```

Since ArticlePreview is a delegator it will delegate to anything passed in the initializer so that is why we can pass in the class or the instance of the Article. However if you ask an instance of `ArticlePreview` what it's `#class` is it returns `ArticlePreview`

**Comment by rapind** [comment]
My 2 cents are that I'm convinced that authorization should be tied to controllers and not models. To that end, namespacing would be nice.

However if the Pundit philosophy is of a model based authorization, then it's almost definitely a bad idea to add namespacing.

**Comment by chendrix** [comment]
Even if we believe that Pundit should be tied to authorization around models and not controllers, **there is such a thing as namespaced models**.

**Comment by chendrix** [comment]
As a potential work around for those trying to get namespaced policies in views, you can do something like:

If you have a `Foo::BarPolicy` and you're trying to access the `show?` method

```Ruby
policy('Foo::Bar'.to_sym).show?
```

**Comment by pascalbetz** [comment]
I'm with @rapind on this one. Having ```self.policy_class``` on the model seems wrong to me. At least in the context of a rails application, where the controller defines the context (Admin::, Api:: namespace), the action (index/show...) as well as the resource (FoosController which might exist inside Admin:: and Api::).

**Comment by edjarris** [comment]
Recently I open an issue to ckeditor gem because I am trying to integrate with pundit https://github.com/galetahub/ckeditor/issues/609. I posted here because I think is related. If someone could bring me some light to the darkness I'll be very greatful :)

Thanks in advance,
