### ISSUE TITLE
unable to find scope SymbolPolicy error

### ISSUE THREAD

**Issue by alec-c4** [varvet/pundit#193]
Sometimes on start rails app i see following error:

```
Pundit::NotDefinedError - unable to find scope SymbolPolicy::Scope for Symbol:
   () Users/alec/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/pundit-165c7f4e5c52/lib/pundit/policy_finder.rb:25:in `scope!'
   () Users/alec/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/pundit-165c7f4e5c52/lib/pundit.rb:26:in `policy_scope!'
  app/policies/application_policy.rb:38:in `scope'
  app/policies/application_policy.rb:14:in `show?'
   () Users/alec/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/pundit-165c7f4e5c52/lib/pundit.rb:70:in `authorize'
  app/controllers/admin/home_controller.rb:3:in `index'
```

but after 3 minutes of waiting after page refresh it went away

**Comment by afkehaya** [comment]
I'm having a similar problem as well. did you ever find a solution. I need help implementing pundit with ActiveAdmin.

**Comment by thomasklemm** [comment]
Try updating `pundit` to `0.3.0` or greater.

**Comment by afkehaya** [comment]
Yeah I have that specified in my gem file. Pundit works fine through out my application except when I added activeadmin. It hasn't been as straight forward to implement there. That could be because I'm newish to ROR. 

I'm really only using pundit for the user facing application and don't need to have authorizations in the admin panel. How can I exclude active admin from pundit?

I already have iclude pundit ..... unless :devise_controller 

How do I block all the controllers in active admin?

**Comment by thomasklemm** [comment]
@afkehaya I'm guessing you're using the [`after_action :verify_authorized`](https://github.com/elabs/pundit#ensuring-policies-are-used) in some controller that your ActiveAdmin controllers inherit from. Use `skip_after_action :verify_authorized` (see the Rails API docs) or create another controller that does not include this `after_action` and inherit from that one. Anyways, this question does not seem to be related to the issue posted above, so please either open a new one or post your questions to StackOverflow.

**Comment by afkehaya** [comment]
Ok thanks for your help @thomasklemm
