### ISSUE TITLE
README has incorrect statement about what #authorize returns

### ISSUE THREAD

**Issue by mackshkatz** [varvet/pundit#467]
And suggests chaining is possible. This isn't correct because #authorize returns true rather than the object passed to it.

This is my first time submitting a change like this, so not sure how I am supposed to go about it, but I forked it and opened a PR against my fork, here is this link, let me know if you need me to do something else, thanks!

https://github.com/elabs/pundit/pull/466

**Comment by pacso** [comment]
Same issue as #439.

If you install from GitHub rather than Rubygems, it'll work fine.

**Comment by hwhelchel** [comment]
@ingemar can we get a new release cut so `authorize` returns the authorize object without having to rely on a commit sha from github or the master branch?

**Comment by pacso** [comment]
I contacted them a couple of times offering to take over maintenance of the gem, but they refused. Their reply stated:

> Thanks for reaching out. I’m sorry that we haven’t been able to keep up with Pundit since Jonas, the creator of Pundit, left the company. But after summer vacations we’ll have a new maintainer, and we’ll dedicate quite a bit of time to clean out the cobwebs.
> 
> Thanks for your patience

That was back in June 2017.

Since then, aside from a few commits and merges, nothing has happened, and no updated build has been released. 

I am now considering this repository effectively dead, and if I need to use pundit in the future I will simply fork the project and maintain my own version. In the mean time, consider using one of the other gems such as cancancan - https://github.com/CanCanCommunity/cancancan

**Comment by Linuus** [comment]
Now the current readme is actually not in sync with the code in master (but it was) :) This is fixed with #511 

I'm currently working through all the issues and PR's to see what we can/should (if any) get into master before cutting a new release.
