### ISSUE TITLE
Support `policy_scope` within POROs

### ISSUE THREAD

**Issue by codebycliff** [varvet/pundit#587]
Lately, I've been extracting a lot of query code to plain old ruby objects. I then `include Pundit` in my object to gain access to `policy_scope`. The problem I'm seeing is I still get a `PolicyScopingNotPerformedError` because I didn't call `policy_scope` directly from the controller. What would the effort be to keep track of policy scoping outside of the controller?

**Comment by Linuus** [comment]
First, `include Pundit` is meant to be used in controllers. Other uses has not been tested and is not supported :)

The tracking of whether the policy scope has been called or not is really simple. It just sets an instance variable in the controller to true, see: https://github.com/varvet/pundit/blob/master/lib/pundit.rb#L249 then in an after action you check if the variable is true, see: https://github.com/varvet/pundit#ensuring-policies-and-scopes-are-used and https://github.com/varvet/pundit/blob/master/lib/pundit.rb#L200-L202

So, I'm not sure we can/want to support tracking this from _anywhere_ in your app out of the box.

You can implement a kind of "after action" hook in your special objects that just do the same checks and raise otherwise I guess.
