### ISSUE TITLE
Authorize collection of records

### ISSUE THREAD

**Issue by welldan97** [varvet/pundit#60]
Hello! Thank you for this nice gem.

Is there a way to authorize an array of items? What is convenient way to do that?

I want to do something like in controller

``` ruby
    authorize array_of_records 
```

because I want to ensure that all records are can be used in current action by current user. And it's not just

``` ruby
   array_of_records.each { |r| authorize r}
```

There is more logic involved in terms how the items in this array are related to each other.

What I think is may be we can have something like

``` ruby
    def self.create?
      ...
    end
```

in policies. And if it is not defined it would just go through each records as I've written upper.

It is possible to get if it is array just by class, also may be it can be ActiveRecord or ActiveRecord::Relation.

What do you think?

P.S. Googling leaded to this [question on SO](http://stackoverflow.com/questions/18338731/authorizing-an-array-of-ids-with-the-pundit-gem), so I guess there is another guy intersted in it

Thanks!

**Comment by iangreenleaf** [comment]
I realize this is a super old issue, but I have a similar use case and wanted to submit one additional quirk in for consideration.

Like the other commenters, I'm receiving a list of IDs and the current user may or may not have permission to "assign" each of these objects. In my case the array is a list of permissions, and we're actually talking about who has permission to assign permissions, which is very meta. But let's stick with the previous example: assigning users to groups.

When you perform an update like this:
```ruby
@group.users = authorized_users
```
you need to check that the current user has permission to manage the users being added to that group. **However**, you may also want to check that the current user has permission to *remove* any other users who were previously in the group. Consider this:

```
@group.ids # => [1, 3, 5]
params[:group][:user_ids] # => [1, 2, 3, 4]
@group.users = authorized_users
```

* I must have permission to manage users 2 and 4 as I am adding them to the group
* I don't actually need permission to manage users 1 and 3 as I am not changing their group membership
* Oops! I also should have had permission to manage user 5 because I just removed them from the group by not including them in the array, but we didn't check!

I'll probably write some sort of helper to manage this process, but it seems like an easy thing to screw up and would be nice if there was some sort of convention for dealing with these sorts of scenarios.

**Comment by tommyalvarez** [comment]
I also need a convetion for handling this type of scenario, for example or batch destroy actions, it may happen that the user is trying to delete a bunch of records, without having permission to destroy **some**  of  those records.
