### ISSUE TITLE
Avoiding N+1s on index pages

### ISSUE THREAD

**Issue by yourtallness** [varvet/pundit#643]
Following the example of the template `ApplicationPolicy`:

```
def show?
  scope.where(id: record.id).exists?
end
```

It would make sense to make actions on one's own resources work similarly, e.g.:

```
def update?
  show? && some_other_condition?(record)
end
```

However checking if `policy(record).update?` on every row of an index page where the displayed rows have already been scoped to the current role (at least with regard to read permission), will result in one EXISTS query per row.

How can we preserve the elegance of using pundit in views to show or hide actions while avoiding N+1 in such a case?

I'm guessing that EXISTS prevents the query from being cached, whereas loading the resources one can update would be cacheable by ActiveRecord.

TIA

**Comment by dgmstuart** [comment]
Thanks for the question. I'm not sure I understand the problem - is this something for Pundit to solve?

I think you're free to define your `update?` however you like - there's nothing forcing you to express it in terms of `show?`, or to otherwise implement it as two separate queries, right?

Quite possibly I'm missing the point.

Also, where is your example from? The default `ApplicationPolicy` just has everything set to false.

**Comment by ce07c3** [comment]
> Following the example of the template `ApplicationPolicy`:
> 
> ```
> def show?
>   scope.where(id: record.id).exists?
> end
> ```
> 
> It would make sense to make actions on one's own resources work similarly, e.g.:
> 
> ```
> def update?
>   show? && some_other_condition?(record)
> end
> ```
> 
> However checking if `policy(record).update?` on every row of an index page where the displayed rows have already been scoped to the current role (at least with regard to read permission), will result in one EXISTS query per row.
> 
> How can we preserve the elegance of using pundit in views to show or hide actions while avoiding N+1 in such a case?
> 
> I'm guessing that EXISTS prevents the query from being cached, whereas loading the resources one can update would be cacheable by ActiveRecord.
> 
> TIA

Create another scope that filters based on update permissions.

```rb
YourPolicy::Scope.new(...).resolve_for_update
```

**Comment by yourtallness** [comment]
@dgmstuart Thanks for the answer.

This is not a pundit issue per se, since the implementation of the methods is left to the integrator as you say. I would normally post this in a Google Group, not the issue queue, but could not find one for this gem.

The only way in which Pundit could be said to influence the developer is that the default generated ApplicationPolicy (in pundit 1.x, I just noticed that in 2.x it has been removed) uses the `exists?` query. If someone follows this example they are likely to run into N+1s.

@ce07c3 Thanks, however this would again result in an N+1 since ActiveRecord will see a different EXISTS query for every record so it won't be able to cache the result based on the query string.

To answer my own question, perhaps it would make sense for the check to be converted to:

`scope.ids.include?(record.id)`

The `scope.ids` query will result in the same SQL for every accessor (and the `includes?` will be evaluated in ruby-land) so I'm guessing AR will cache it.
Will do some testing to confirm this.

It might be a useful addition to the wiki on how to write a good policy or something.

**Comment by ce07c3** [comment]
@yourtallness not quite; you just need to use the scope for collections and the update? check for single records. As intended.

**Comment by Burgestrand** [comment]
It's tempting to try to define the policy by using the scope or vice-versa, and in practice a lot of the time it leads to problems like this. Depending what your rules are you might be able to make it work, but in the general case it's not something we recommend doing which is why it was removed from the template.

You appear to have already figured this all out, so I'm mostly leaving this note for future friends coming along and reading this.
