### ISSUE TITLE
Combined authorization and scoping

### ISSUE THREAD

**Issue by sedubois** [varvet/pundit#648]
In https://github.com/varvet/pundit/issues/595 @Linuus explains why `authorize` and `policy_scope` are dealt with separately. My understanding is that `authorize` is more an API for individual resources and `policy_scope` is more for collections.

However I've come to rely on scoping for collections as well as individual records, e.g. to filter published records or to eager join tables such as ActiveStorage attachments or Globalize translations.

To avoid every time calling `authorize` + `policy_scope` as well as `verify_authorized` + `verify_policy_scoped`, one might extend the authorization to take care of scoping:
```rb
class Model
  translates :name
  has_one_attached :image
end

class ModelPolicy < ApplicationPolicy
  def index?
    ...
  end

  def show?
    ...
  end

  class Scope < Scope
    def resolve
      super
        .published
        .with_translations(I18n.locale)
        .with_attached_image
    end
  end
end

class ApplicationController < ActionController::Base
  include Pundit
  ...
  
  def authorize(record, query = nil, policy_class: nil)
    scoped_record = policy_scope super
    block_given? ? yield(scoped_record) : scoped_record
  end

  def verify_authorized
    super && verify_policy_scoped
  end
end

class ModelsController < ApplicationController
  after_action :verify_authorized

  def index
    @models = authorize Model
  end

  def show
    @model = authorize Model { |scope| scope.find(params[:id]) }
  end
end
```

The scoping is applied after authorization, so it should ensure that the DB is only accessed if needed.

What do you think of the above? Would it be worthwhile to have such a feature in Pundit?

**Comment by dgmstuart** [comment]
Thanks for the suggestion.

While this is an interesting approach, we're not open to extending the scope of Pundit at this point.

There are also a couple of issues with the way that scopes relate to authorization of actions:

1. While `index?`, `edit?`, `update?`, `delete?` and maybe `show?` have clear corresponding scopes (eg. "Can I update this record" and "what is the list of records I can update?"), it's at least less clear what a scope would mean for `new?` and  `create?`
2. Just because a record is returned in the scope, it doesn't necessarily mean that you're allowed to perform any particular action on that record. 

Or rather, if you want to define authorization in terms of scopes then maybe [Moat](https://github.com/polleverywhere/moat) would be a better fit for you.
