### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by iMacTia** [varvet/pundit#656]
Latest release was August 2019, and since then there have been lots of commits in `master`.
Would the team consider releasing a new version with all the new fixes/features?

**Comment by rlue** [comment]
Wait up! There are some commits in `master` that extend the API in a way that I and at least one other person [don't think are ideal](https://github.com/varvet/pundit/pull/655#issuecomment-632454600)—if a new release is coming, is there any chance we could get some feedback on #654 / #655 first? :pray:

**Comment by iMacTia** [comment]
I understand the pending issues but the last release is almost 1 year old now and there hasn't been any movement on those issues since May/June 😕...

**Comment by rlue** [comment]
If it helps, you can just [specify the commit you need in your Gemfile](https://bundler.io/guides/git.html#how-to-install-gems-from-git-repositories):

```ruby
gem 'pundit', git: 'https://github.com/varvet/pundit.git', ref: '504b86a'
```

**Comment by iMacTia** [comment]
Of course! I did it back in May, but I hope you'll agree that's not a long-term solution 😅
I was hoping to see a proper release in a few weeks, definitely not expecting months!

**Comment by vpereira** [comment]
I'm looking forward for a new release, specially because of https://github.com/varvet/pundit/blob/master/lib/pundit.rb#L24-L41. Any plans for 2020?

**Comment by mabras** [comment]
If anyone search for alternative:
https://actionpolicy.evilmartians.io/

**Comment by gat-bryszard** [comment]
Any news in here? It doesn't look good with the last meaningful commit 17 months ago.

**Comment by athix** [comment]
@kindell @olleolleolle @dgmstuart 

What are the long term plans for Pundit? I was planning on using Pundit as the primary example of Authorization combined with Sorcery as the Authentication, but it is a bit concerning if the release cadence is looking unhealthy.

**Comment by Burgestrand** [comment]
Hi! I can't speak for the other maintainers, but I can give you some information from Varvet. This is all preliminary as we're still figuring things out at Varvet, and I can't run this post by @kindell or @dgmstuart since they're both (me too, really) on ~4-week swedish vacation and are off-grid right now. Please keep some spare oversight in hand while reading this.

That said, I just noticed this issue and I figured a vague reply is better than none.

**The short answer** is that we at Varvet have no intention of abandoning Pundit. It's likely that we'll continue spending resources on Pundit, and if that turns out to not be an alternative we are probably looking at finding a new maintainer.

The long answer is that recently (~mars 2020) Varvet as a company underwent a significant restart. We're a much smaller shop now, so @dgmstuart and I started doing inventory of our OSS projects and trying to figure out what to do with all of them. Most of the time until now has been spent on building up and getting to know the new company we just rebooted, and our public communications suffered. I'm sorry.

I can't do much right at this moment, but I can promise I'll take a closer look together with @dgmstuart late august when we're both back from vacation and are on-grid again.

**Comment by Burgestrand** [comment]
> Wait up! There are some commits in `master` that extend the API in a way that I and at least one other person [don't think are ideal](https://github.com/varvet/pundit/pull/655#issuecomment-632454600)—if a new release is coming, is there any chance we could get some feedback on #654 / #655 first? 🙏

Agreed. That said, it shouldn't keep us from making a new release. We'll revert the change in master in order to make a new release right away.

As for error reasons/messages that discussion can move to https://github.com/varvet/pundit/issues/654 for now.

**Comment by Burgestrand** [comment]
Hi again!

[The new release is out](https://github.com/varvet/pundit/blob/master/CHANGELOG.md#211-2021-08-13) and available on Rubygems. It has a bugfix that might break existing code, so be careful.
