### ISSUE TITLE
current_user.can? helpers

### ISSUE THREAD

**Issue by aaronchi** [varvet/pundit#76]
After setting up pundit, I found it inconvenient to use the default 'policy' helper in views as I would often be testing for authorizations against different models than the one loaded by the controller. I like the current_user.can_xxx? syntax used in many authorization libraries so I came up with a simple concern to add these helpers to a user model.

It can be cleaned up a bit but is this something that might be accepted into the library if I put together a pull request?

```
module PunditUser

  extend ActiveSupport::Concern

  def method_missing(meth, *args)
    if meth.to_s =~ /^can_(.+)$/
      Pundit.policy!(self, *args).send(meth.to_s.sub(/^can_/,''))
    else
      super
    end
  end

end
```

**Comment by stephenorr** [comment]
Sorry to resurrect an old thread, but I've just started using Pundit, and I was inspired by this idea.

I've simply defined a `can?` method on my User model, as follows:

```ruby
def can?(action, object)
  begin
    policy_method = "#{action.to_s}?"
    Pundit.policy!(self, object).send(policy_method)
  rescue NoMethodError => e
    policy_name = "#{object.name.to_s}Policy"
    logger.debug "Undefined Pundit policy method: #{policy_name}##{policy_method}, returned false by default"
    false
  end
end
```

This gives me about as much magic as I need, because the goal was to be able to do the following in the view when I'm trying to render items for a global navigation menu:

```ruby
<% if current_user.can?(:search, User) %>
  <%= link_to "Users", users_path %>
<% else %>
  Users
<% end %>
```

Thanks for a great gem @jnicklas, the lack of magic is helpful to my understanding of it so far.
