### ISSUE TITLE
pundit cant find policy while using namespace

### ISSUE THREAD

**Issue by Sphaerus** [varvet/pundit#94]
I'm using standard "admin" namespace, yet if i use 'authorize' method in it, pundit still looks for "standard" class.
eg i have admin::userscontroller, and in my policies, directory 'admin' with admin::userpolicy but all the time i get 
'unable to find policy UserPolicy' error.

**Comment by jekuno** [comment]
I had a similar issue. If you have a `Admin::User` model you may not use a simple symbol such as `authorize :user` because pundits policy finder will turn this into `User` (namespace missing) using `object.to_s.camelize`.

Check your parameter of the `authorize` call. You either have to provide an instance of your class such as `authorize Admin::User.new` or you need to provide a prefixed symbol such as `authorize :"admin/user"`.

**Comment by rolandoalvarado** [comment]
This solves my issue. Thanks @jnicklas
